theme: jekyll-theme-cayman
title: the nest.

tag_schema:
  epistemic:
    - endorsed
    - disputed
    - disputed-author
    - surprising
    - influential

  form:
    - charity
    - album
    - book
    - organization
    - blog
    - channel
    - browser-extension

  cw:
    - cw
    - nsfw
