theme: jekyll-theme-cayman
title: the nest.
permalink: pretty
tag_schema:
  epistemic:
    - endorsed
    - disputed
    - disputed-author
    - surprising
    - influential

  form:
    - charity
    - album
    - book
    - organization
    - blog
    - channel
    - browser-extension
    - dataset

  cw:
    - cw
    - nsfw
